// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconList: typeof import('./src/components/home/IconList.vue')['default']
    ItemMusicTop: typeof import('./src/components/item/ItemMusicTop.vue')['default']
    MusicList: typeof import('./src/components/home/MusicList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwpierTop: typeof import('./src/components/home/SwpierTop.vue')['default']
    TopNav: typeof import('./src/components/home/TopNav.vue')['default']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
  }
}
